/*USE sql_store;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT points 
FROM customers 
WHERE customer_id=1;*/
/*USE sql_store;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SELECT points 
FROM customers 
WHERE customer_id=1;*/
/*USE sql_store;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
SELECT points FROM customers WHERE customer_id=1;
SELECT points FROM customers WHERE customer_id=1;
COMMIT;*/
/*USE sql_store;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
START TRANSACTION;
SELECT points FROM customers WHERE customer_id=1;
SELECT points FROM customers WHERE customer_id=1;
COMMIT;*/
/*SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
START TRANSACTION;
SELECT * FROM customers WHERE state='VA';
COMMIT;*/
SET TRANSACTION ISOLATION LEVEL serializable;
START TRANSACTION;
SELECT * FROM customers WHERE state='VA';
COMMIT;
